# 03_build_index.ipynb

Chunked FAISS embedding index build.
Only the embedding/index creation part is changed to avoid RAM overflow.
Project imports and preprocessing follow the existing notebooks.

In [4]:
from pathlib import Path
import sys
import pandas as pd

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))
    
import gc
import glob

import pandas as pd
import numpy as np
import faiss

from src.rag.config import load_config
from src.rag.utils.text import build_comment_text
from src.rag.preprocessing.processor import TextProcessor
from src.rag.embedding.factory import EmbeddingFactory

In [5]:
config = load_config(
    "../configs/rag.yaml"
)

config

{'retrieval': {'type': 'hybrid',
  'top_k': 5,
  'hybrid': {'bm25_weight': 0.3, 'embedding_weight': 0.7}},
 'embedding': {'provider': 'sentence_transformer',
  'model': 'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2'}}

In [6]:
comments = pd.read_parquet(
    "../data/processed/comments_clean.parquet"
)

comments.head()

,id,title,body,created_at,rate,recommendation_status,is_buyer,product_id,advantages,disadvantages,likes,dislikes,seller_title,seller_code,true_to_size_rate,created_at_gregorian
0,14144758,هری پاتر,عالیه مخصوصا طرحش عکس مجموعه هری پاترم رو میزا...,10 آذر 1399,5.0,recommended,True,1075274,NaN,NaN,1136,8,بیگای استودیو,5AADE,NaN,2020-11-30
1,41782279,روغن ریش,توجه فرمایید که عکس اول واسه ۲ هفته پیشه و عکس...,21 آبان 1401,3.0,recommended,True,6081008,NaN,NaN,896,79,گراندو بیوتی,6XN5S,NaN,2022-11-12
2,49569443,تقلبی,متاسفانه از سال ۹۶ مشتری دیجیکالا هستم.بالای ۴...,3 خرداد 1402,1.0,not_recommended,True,10545754,NaN,NaN,625,60,کافه سرگرمی,AXVST,NaN,2023-05-24
3,43932524,یک نظر بی اغراق!,تصمیم خرید کنسول برای منِ 32 ساله با هزینه شخص...,15 دی 1401,5.0,recommended,True,4153832,NaN,NaN,524,51,گروه آروند,5AD65,NaN,2023-01-05
4,21396693,NaN,اول لاک معمولی میزدم و بعد از خشک شدن کامل این...,9 خرداد 1400,3.0,no_idea,True,2185657,NaN,NaN,450,2,تاباتا,C93UM,NaN,2021-05-30

In [7]:
processor = TextProcessor()


comments["search_text"] = (
    comments
    .apply(build_comment_text, axis=1)
    .apply(processor.process)
)


documents = comments[
    [
        "id",
        "product_id",
        "body",
        "rate",
        "search_text"
    ]
].copy()


documents.head()

,id,product_id,body,rate,search_text
0,14144758,1075274,عالیه مخصوصا طرحش عکس مجموعه هری پاترم رو میزا...,5.0,هری پاتر عالیه مخصوصا طرحش عکس مجموعه هری پاتر...
1,41782279,6081008,توجه فرمایید که عکس اول واسه ۲ هفته پیشه و عکس...,3.0,روغن ریش توجه فرمایید که عکس اول واسه ۲ هفته پ...
2,49569443,10545754,متاسفانه از سال ۹۶ مشتری دیجیکالا هستم.بالای ۴...,1.0,تقلبی متاسفانه از سال ۹۶ مشتری دیجیکالا هستم.ب...
3,43932524,4153832,تصمیم خرید کنسول برای منِ 32 ساله با هزینه شخص...,5.0,یک نظر بی اغراق! تصمیم خرید کنسول برای منِ 32 ...
4,21396693,2185657,اول لاک معمولی میزدم و بعد از خشک شدن کامل این...,3.0,اول لاک معمولی میزدم و بعد از خشک شدن کامل این...

In [8]:
embedding_model = EmbeddingFactory.create(
    config["embedding"]["provider"],
    config["embedding"]["model"]
)

embedding_model

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 8621.70it/s]

In [10]:
index_dir = Path(
    "../data/indexes/product_comments_embedding"
)

chunk_dir = index_dir / "chunks"

chunk_dir.mkdir(
    parents=True,
    exist_ok=True
)


batch_size = 5000
encode_batch_size = 64


texts = (
    documents["search_text"]
    .fillna("")
    .astype(str)
    .tolist()
)

In [11]:
for start in range(
    0,
    len(texts),
    batch_size
):

    end = min(
        start + batch_size,
        len(texts)
    )

    print(
        f"Encoding {start}:{end}"
    )


    embeddings = embedding_model.encode(
        texts[start:end],
        device="cuda",
        batch_size=encode_batch_size
    )


    embeddings = np.asarray(
        embeddings
    ).astype("float32")


    faiss.normalize_L2(
        embeddings
    )


    chunk_index = faiss.IndexFlatIP(
        embeddings.shape[1]
    )

    chunk_index.add(
        embeddings
    )


    faiss.write_index(
        chunk_index,
        str(chunk_dir / f"chunk_{start}.faiss")
    )


    del embeddings
    del chunk_index

    gc.collect()


print("All chunks saved")

Encoding 0:5000
Encoding 5000:10000
Encoding 10000:15000
Encoding 15000:20000
Encoding 20000:25000
Encoding 25000:30000
Encoding 30000:35000
Encoding 35000:40000
Encoding 40000:45000
Encoding 45000:50000
Encoding 50000:55000
Encoding 55000:60000
Encoding 60000:65000
Encoding 65000:70000
Encoding 70000:75000
Encoding 75000:80000
Encoding 80000:85000
Encoding 85000:90000
Encoding 90000:95000
Encoding 95000:100000
Encoding 100000:105000
Encoding 105000:110000
Encoding 110000:115000
Encoding 115000:120000
Encoding 120000:125000
Encoding 125000:130000
Encoding 130000:135000
Encoding 135000:140000
Encoding 140000:145000
Encoding 145000:150000
Encoding 150000:155000
Encoding 155000:160000
Encoding 160000:165000
Encoding 165000:170000
Encoding 170000:175000
Encoding 175000:180000
Encoding 180000:185000
Encoding 185000:190000
Encoding 190000:195000
Encoding 195000:200000
Encoding 200000:205000
Encoding 205000:210000
Encoding 210000:215000
Encoding 215000:220000
Encoding 220000:225000
Encoding 225000:230000
Encoding 230000:235000
Encoding 235000:240000
Encoding 240000:245000
Encoding 245000:250000
Encoding 250000:255000
Encoding 255000:260000
Encoding 260000:265000
Encoding 265000:270000
Encoding 270000:275000
Encoding 275000:280000
Encoding 280000:285000
Encoding 285000:290000
Encoding 290000:295000
Encoding 295000:300000
Encoding 300000:305000
Encoding 305000:310000
Encoding 310000:315000
Encoding 315000:320000
Encoding 320000:325000
Encoding 325000:330000
Encoding 330000:335000
Encoding 335000:340000
Encoding 340000:345000
Encoding 345000:350000
Encoding 350000:355000
Encoding 355000:360000
Encoding 360000:365000
Encoding 365000:370000
Encoding 370000:375000
Encoding 375000:380000
Encoding 380000:385000
Encoding 385000:390000
Encoding 390000:395000
Encoding 395000:400000
Encoding 400000:405000
Encoding 405000:410000
Encoding 410000:415000
Encoding 415000:420000
Encoding 420000:425000
Encoding 425000:430000
Encoding 430000:435000
Encoding 435000:440000
Encoding 440000:445000
Encoding 445000:450000
Encoding 450000:455000
Encoding 455000:460000
Encoding 460000:465000
Encoding 465000:470000
Encoding 470000:475000
Encoding 475000:480000
Encoding 480000:485000
Encoding 485000:490000
Encoding 490000:495000
Encoding 495000:500000
Encoding 500000:505000
Encoding 505000:510000
Encoding 510000:515000
Encoding 515000:520000
Encoding 520000:525000
Encoding 525000:530000
Encoding 530000:535000
Encoding 535000:540000
Encoding 540000:545000
Encoding 545000:550000
Encoding 550000:555000
Encoding 555000:560000
Encoding 560000:565000
Encoding 565000:570000
Encoding 570000:575000
Encoding 575000:580000
Encoding 580000:585000
Encoding 585000:590000
Encoding 590000:595000
Encoding 595000:600000
Encoding 600000:605000
Encoding 605000:610000
Encoding 610000:615000
Encoding 615000:620000
Encoding 620000:625000
Encoding 625000:630000
Encoding 630000:635000
Encoding 635000:640000
Encoding 640000:645000
Encoding 645000:650000
Encoding 650000:655000
Encoding 655000:660000
Encoding 660000:665000
Encoding 665000:670000
Encoding 670000:675000
Encoding 675000:680000
Encoding 680000:685000
Encoding 685000:690000
Encoding 690000:695000
Encoding 695000:700000
Encoding 700000:705000
Encoding 705000:710000
Encoding 710000:715000
Encoding 715000:720000
Encoding 720000:725000
Encoding 725000:730000
Encoding 730000:735000
Encoding 735000:740000
Encoding 740000:745000
Encoding 745000:750000
Encoding 750000:755000
Encoding 755000:760000
Encoding 760000:765000
Encoding 765000:770000
Encoding 770000:775000
Encoding 775000:780000
Encoding 780000:785000
Encoding 785000:790000
Encoding 790000:795000
Encoding 795000:800000
Encoding 800000:805000
Encoding 805000:810000
Encoding 810000:815000
Encoding 815000:820000
Encoding 820000:825000
Encoding 825000:830000
Encoding 830000:835000
Encoding 835000:840000
Encoding 840000:845000
Encoding 845000:850000
Encoding 850000:855000
Encoding 855000:860000
Encoding 860000:865000
Encoding 865000:870000
Encoding 870000:875000
Encoding 875000:880000
Encoding 880000:885000
Encoding 885000:890000
Encoding 890000:895000
Encoding 895000:900000
Encoding 900000:905000
Encoding 905000:910000
Encoding 910000:915000
Encoding 915000:920000
Encoding 920000:925000
Encoding 925000:930000
Encoding 930000:935000
Encoding 935000:940000
Encoding 940000:945000
Encoding 945000:950000
Encoding 950000:955000
Encoding 955000:960000
Encoding 960000:965000
Encoding 965000:970000
Encoding 970000:975000
Encoding 975000:980000
Encoding 980000:985000
Encoding 985000:990000
Encoding 990000:995000
Encoding 995000:1000000
Encoding 1000000:1005000
Encoding 1005000:1010000
Encoding 1010000:1015000
Encoding 1015000:1020000
Encoding 1020000:1025000
Encoding 1025000:1030000
Encoding 1030000:1035000
Encoding 1035000:1040000
Encoding 1040000:1045000
Encoding 1045000:1050000
Encoding 1050000:1055000
Encoding 1055000:1060000
Encoding 1060000:1065000
Encoding 1065000:1070000
Encoding 1070000:1075000
Encoding 1075000:1080000
Encoding 1080000:1085000
Encoding 1085000:1090000
Encoding 1090000:1095000
Encoding 1095000:1100000
Encoding 1100000:1105000
Encoding 1105000:1110000
Encoding 1110000:1115000
Encoding 1115000:1120000
Encoding 1120000:1125000
Encoding 1125000:1130000
Encoding 1130000:1135000
Encoding 1135000:1140000
Encoding 1140000:1145000
Encoding 1145000:1150000
Encoding 1150000:1155000
Encoding 1155000:1160000
Encoding 1160000:1165000
Encoding 1165000:1170000
Encoding 1170000:1175000
Encoding 1175000:1180000
Encoding 1180000:1185000
Encoding 1185000:1190000
Encoding 1190000:1195000
Encoding 1195000:1200000
Encoding 1200000:1205000
Encoding 1205000:1210000
Encoding 1210000:1215000
Encoding 1215000:1220000
Encoding 1220000:1225000
Encoding 1225000:1230000
Encoding 1230000:1235000
Encoding 1235000:1240000
Encoding 1240000:1245000
Encoding 1245000:1250000
Encoding 1250000:1255000
Encoding 1255000:1260000
Encoding 1260000:1265000
Encoding 1265000:1270000
Encoding 1270000:1275000
Encoding 1275000:1280000
Encoding 1280000:1285000
Encoding 1285000:1290000
Encoding 1290000:1295000
Encoding 1295000:1300000
Encoding 1300000:1305000
Encoding 1305000:1310000
Encoding 1310000:1315000
Encoding 1315000:1320000
Encoding 1320000:1325000
Encoding 1325000:1330000
Encoding 1330000:1335000
Encoding 1335000:1340000
Encoding 1340000:1345000
Encoding 1345000:1350000
Encoding 1350000:1355000
Encoding 1355000:1360000
Encoding 1360000:1365000
Encoding 1365000:1370000
Encoding 1370000:1375000
Encoding 1375000:1380000
Encoding 1380000:1385000
Encoding 1385000:1390000
Encoding 1390000:1395000
Encoding 1395000:1400000
Encoding 1400000:1405000
Encoding 1405000:1410000
Encoding 1410000:1415000
Encoding 1415000:1420000
Encoding 1420000:1425000
Encoding 1425000:1430000
Encoding 1430000:1435000
Encoding 1435000:1440000
Encoding 1440000:1445000
Encoding 1445000:1450000
Encoding 1450000:1455000
Encoding 1455000:1460000
Encoding 1460000:1465000
Encoding 1465000:1470000
Encoding 1470000:1475000
Encoding 1475000:1480000
Encoding 1480000:1485000
Encoding 1485000:1490000
Encoding 1490000:1495000
Encoding 1495000:1500000
Encoding 1500000:1505000
Encoding 1505000:1510000
Encoding 1510000:1515000
Encoding 1515000:1520000
Encoding 1520000:1525000
Encoding 1525000:1530000
Encoding 1530000:1535000
Encoding 1535000:1540000
Encoding 1540000:1545000
Encoding 1545000:1550000
Encoding 1550000:1555000
Encoding 1555000:1560000
Encoding 1560000:1565000
Encoding 1565000:1570000
Encoding 1570000:1575000
Encoding 1575000:1580000
Encoding 1580000:1585000
Encoding 1585000:1590000
Encoding 1590000:1595000
Encoding 1595000:1600000
Encoding 1600000:1605000
Encoding 1605000:1610000
Encoding 1610000:1615000
Encoding 1615000:1620000
Encoding 1620000:1625000
Encoding 1625000:1630000
Encoding 1630000:1635000
Encoding 1635000:1640000
Encoding 1640000:1645000
Encoding 1645000:1650000
Encoding 1650000:1655000
Encoding 1655000:1660000
Encoding 1660000:1665000
Encoding 1665000:1670000
Encoding 1670000:1675000
Encoding 1675000:1680000
Encoding 1680000:1685000
Encoding 1685000:1690000
Encoding 1690000:1695000
Encoding 1695000:1700000
Encoding 1700000:1705000
Encoding 1705000:1710000
Encoding 1710000:1715000
Encoding 1715000:1720000
Encoding 1720000:1725000
Encoding 1725000:1730000
Encoding 1730000:1735000
Encoding 1735000:1740000
Encoding 1740000:1745000
Encoding 1745000:1750000
Encoding 1750000:1755000
Encoding 1755000:1760000
Encoding 1760000:1765000
Encoding 1765000:1770000
Encoding 1770000:1775000
Encoding 1775000:1780000
Encoding 1780000:1785000
Encoding 1785000:1790000
Encoding 1790000:1795000
Encoding 1795000:1800000
Encoding 1800000:1805000
Encoding 1805000:1810000
Encoding 1810000:1815000
Encoding 1815000:1820000
Encoding 1820000:1825000
Encoding 1825000:1830000
Encoding 1830000:1835000
Encoding 1835000:1840000
Encoding 1840000:1845000
Encoding 1845000:1850000
Encoding 1850000:1855000
Encoding 1855000:1860000
Encoding 1860000:1865000
Encoding 1865000:1870000
Encoding 1870000:1875000
Encoding 1875000:1880000
Encoding 1880000:1885000
Encoding 1885000:1890000
Encoding 1890000:1895000
Encoding 1895000:1900000
Encoding 1900000:1905000
Encoding 1905000:1910000
Encoding 1910000:1915000
Encoding 1915000:1920000
Encoding 1920000:1925000
Encoding 1925000:1930000
Encoding 1930000:1935000
Encoding 1935000:1940000
Encoding 1940000:1945000
Encoding 1945000:1950000
Encoding 1950000:1955000
Encoding 1955000:1960000
Encoding 1960000:1965000
Encoding 1965000:1970000
Encoding 1970000:1975000
Encoding 1975000:1980000
Encoding 1980000:1985000
Encoding 1985000:1990000
Encoding 1990000:1995000
Encoding 1995000:2000000
Encoding 2000000:2005000
Encoding 2005000:2010000
Encoding 2010000:2015000
Encoding 2015000:2020000
Encoding 2020000:2025000
Encoding 2025000:2030000
Encoding 2030000:2035000
Encoding 2035000:2040000
Encoding 2040000:2045000
Encoding 2045000:2050000
Encoding 2050000:2055000
Encoding 2055000:2060000
Encoding 2060000:2065000
Encoding 2065000:2070000
Encoding 2070000:2075000
Encoding 2075000:2080000
Encoding 2080000:2085000
Encoding 2085000:2090000
Encoding 2090000:2095000
Encoding 2095000:2100000
Encoding 2100000:2105000
Encoding 2105000:2110000
Encoding 2110000:2115000
Encoding 2115000:2120000
Encoding 2120000:2125000
Encoding 2125000:2130000
Encoding 2130000:2135000
Encoding 2135000:2140000
Encoding 2140000:2145000
Encoding 2145000:2150000
Encoding 2150000:2155000
Encoding 2155000:2160000
Encoding 2160000:2165000
Encoding 2165000:2170000
Encoding 2170000:2175000
Encoding 2175000:2180000
Encoding 2180000:2185000
Encoding 2185000:2190000
Encoding 2190000:2195000
Encoding 2195000:2200000
Encoding 2200000:2205000
Encoding 2205000:2210000
Encoding 2210000:2215000
Encoding 2215000:2220000
Encoding 2220000:2225000
Encoding 2225000:2230000
Encoding 2230000:2235000
Encoding 2235000:2240000
Encoding 2240000:2245000
Encoding 2245000:2250000
Encoding 2250000:2255000
Encoding 2255000:2260000
Encoding 2260000:2265000
Encoding 2265000:2270000
Encoding 2270000:2275000
Encoding 2275000:2280000
Encoding 2280000:2285000
Encoding 2285000:2290000
Encoding 2290000:2295000
Encoding 2295000:2300000
Encoding 2300000:2305000
Encoding 2305000:2310000
Encoding 2310000:2315000
Encoding 2315000:2320000
Encoding 2320000:2325000
Encoding 2325000:2330000
Encoding 2330000:2335000
Encoding 2335000:2340000
Encoding 2340000:2345000
Encoding 2345000:2350000
Encoding 2350000:2355000
Encoding 2355000:2360000
Encoding 2360000:2365000
Encoding 2365000:2370000
Encoding 2370000:2375000
Encoding 2375000:2380000
Encoding 2380000:2385000
Encoding 2385000:2390000
Encoding 2390000:2395000
Encoding 2395000:2400000
Encoding 2400000:2405000
Encoding 2405000:2410000
Encoding 2410000:2415000
Encoding 2415000:2420000
Encoding 2420000:2425000
Encoding 2425000:2430000
Encoding 2430000:2435000
Encoding 2435000:2440000
Encoding 2440000:2445000
Encoding 2445000:2450000
Encoding 2450000:2455000
Encoding 2455000:2460000
Encoding 2460000:2465000
Encoding 2465000:2470000
Encoding 2470000:2475000
Encoding 2475000:2480000
Encoding 2480000:2485000
Encoding 2485000:2490000
Encoding 2490000:2495000
Encoding 2495000:2500000
Encoding 2500000:2505000
Encoding 2505000:2510000
Encoding 2510000:2515000
Encoding 2515000:2520000
Encoding 2520000:2525000
Encoding 2525000:2530000
Encoding 2530000:2535000
Encoding 2535000:2540000
Encoding 2540000:2545000
Encoding 2545000:2550000
Encoding 2550000:2555000
Encoding 2555000:2560000
Encoding 2560000:2565000
Encoding 2565000:2570000
Encoding 2570000:2575000
Encoding 2575000:2580000
Encoding 2580000:2585000
Encoding 2585000:2590000
Encoding 2590000:2595000
Encoding 2595000:2600000
Encoding 2600000:2605000
Encoding 2605000:2610000
Encoding 2610000:2615000
Encoding 2615000:2620000
Encoding 2620000:2625000
Encoding 2625000:2630000
Encoding 2630000:2635000
Encoding 2635000:2640000
Encoding 2640000:2645000
Encoding 2645000:2650000
Encoding 2650000:2655000
Encoding 2655000:2660000
Encoding 2660000:2665000
Encoding 2665000:2670000
Encoding 2670000:2675000
Encoding 2675000:2680000
Encoding 2680000:2685000
Encoding 2685000:2690000
Encoding 2690000:2695000
Encoding 2695000:2700000
Encoding 2700000:2705000
Encoding 2705000:2710000
Encoding 2710000:2715000
Encoding 2715000:2720000
Encoding 2720000:2725000
Encoding 2725000:2730000
Encoding 2730000:2735000
Encoding 2735000:2740000
Encoding 2740000:2745000
Encoding 2745000:2750000
Encoding 2750000:2755000
Encoding 2755000:2760000
Encoding 2760000:2765000
Encoding 2765000:2770000
Encoding 2770000:2775000
Encoding 2775000:2780000
Encoding 2780000:2785000
Encoding 2785000:2790000
Encoding 2790000:2795000
Encoding 2795000:2800000
Encoding 2800000:2805000
Encoding 2805000:2810000
Encoding 2810000:2815000
Encoding 2815000:2820000
Encoding 2820000:2825000
Encoding 2825000:2830000
Encoding 2830000:2835000
Encoding 2835000:2840000
Encoding 2840000:2845000
Encoding 2845000:2850000
Encoding 2850000:2855000
Encoding 2855000:2860000
Encoding 2860000:2865000
Encoding 2865000:2870000
Encoding 2870000:2875000
Encoding 2875000:2880000
Encoding 2880000:2885000
Encoding 2885000:2890000
Encoding 2890000:2895000
Encoding 2895000:2900000
Encoding 2900000:2905000
Encoding 2905000:2910000
Encoding 2910000:2915000
Encoding 2915000:2920000
Encoding 2920000:2925000
Encoding 2925000:2930000
Encoding 2930000:2935000
Encoding 2935000:2940000
Encoding 2940000:2945000
Encoding 2945000:2950000
Encoding 2950000:2955000
Encoding 2955000:2960000
Encoding 2960000:2965000
Encoding 2965000:2970000
Encoding 2970000:2975000
Encoding 2975000:2980000
Encoding 2980000:2985000
Encoding 2985000:2990000
Encoding 2990000:2995000
Encoding 2995000:3000000
Encoding 3000000:3005000
Encoding 3005000:3010000
Encoding 3010000:3015000
Encoding 3015000:3020000
Encoding 3020000:3025000
Encoding 3025000:3030000
Encoding 3030000:3035000
Encoding 3035000:3040000
Encoding 3040000:3045000
Encoding 3045000:3050000
Encoding 3050000:3055000
Encoding 3055000:3060000
Encoding 3060000:3065000
Encoding 3065000:3070000
Encoding 3070000:3075000
Encoding 3075000:3080000
Encoding 3080000:3085000
Encoding 3085000:3090000
Encoding 3090000:3095000
Encoding 3095000:3100000
Encoding 3100000:3105000
Encoding 3105000:3110000
Encoding 3110000:3115000
Encoding 3115000:3120000
Encoding 3120000:3125000
Encoding 3125000:3130000
Encoding 3130000:3135000
Encoding 3135000:3140000
Encoding 3140000:3145000
Encoding 3145000:3150000
Encoding 3150000:3155000
Encoding 3155000:3160000
Encoding 3160000:3165000
Encoding 3165000:3170000
Encoding 3170000:3175000
Encoding 3175000:3180000
Encoding 3180000:3185000
Encoding 3185000:3190000
Encoding 3190000:3195000
Encoding 3195000:3200000
Encoding 3200000:3205000
Encoding 3205000:3210000
Encoding 3210000:3215000
Encoding 3215000:3220000
Encoding 3220000:3225000
Encoding 3225000:3230000
Encoding 3230000:3235000
Encoding 3235000:3240000
Encoding 3240000:3245000
Encoding 3245000:3250000
Encoding 3250000:3255000
Encoding 3255000:3260000
Encoding 3260000:3265000
Encoding 3265000:3270000
Encoding 3270000:3275000
Encoding 3275000:3280000
Encoding 3280000:3285000
Encoding 3285000:3290000
Encoding 3290000:3295000
Encoding 3295000:3300000
Encoding 3300000:3305000
Encoding 3305000:3310000
Encoding 3310000:3315000
Encoding 3315000:3320000
Encoding 3320000:3325000
Encoding 3325000:3330000
Encoding 3330000:3335000
Encoding 3335000:3340000
Encoding 3340000:3345000
Encoding 3345000:3350000
Encoding 3350000:3355000
Encoding 3355000:3360000
Encoding 3360000:3365000
Encoding 3365000:3370000
Encoding 3370000:3375000
Encoding 3375000:3380000
Encoding 3380000:3385000
Encoding 3385000:3390000
Encoding 3390000:3395000
Encoding 3395000:3400000
Encoding 3400000:3405000
Encoding 3405000:3410000
Encoding 3410000:3415000
Encoding 3415000:3420000
Encoding 3420000:3425000
Encoding 3425000:3430000
Encoding 3430000:3435000
Encoding 3435000:3440000
Encoding 3440000:3445000
Encoding 3445000:3450000
Encoding 3450000:3455000
Encoding 3455000:3460000
Encoding 3460000:3465000
Encoding 3465000:3470000
Encoding 3470000:3475000
Encoding 3475000:3480000
Encoding 3480000:3485000
Encoding 3485000:3490000
Encoding 3490000:3495000
Encoding 3495000:3500000
Encoding 3500000:3505000
Encoding 3505000:3510000
Encoding 3510000:3515000
Encoding 3515000:3520000
Encoding 3520000:3525000
Encoding 3525000:3530000
Encoding 3530000:3535000
Encoding 3535000:3540000
Encoding 3540000:3545000
Encoding 3545000:3550000
Encoding 3550000:3555000
Encoding 3555000:3560000
Encoding 3560000:3565000
Encoding 3565000:3570000
Encoding 3570000:3575000
Encoding 3575000:3580000
Encoding 3580000:3585000
Encoding 3585000:3590000
Encoding 3590000:3595000
Encoding 3595000:3600000
Encoding 3600000:3605000
Encoding 3605000:3610000
Encoding 3610000:3615000
Encoding 3615000:3620000
Encoding 3620000:3625000
Encoding 3625000:3630000
Encoding 3630000:3635000
Encoding 3635000:3640000
Encoding 3640000:3645000
Encoding 3645000:3650000
Encoding 3650000:3655000
Encoding 3655000:3660000
Encoding 3660000:3665000
Encoding 3665000:3670000
Encoding 3670000:3675000
Encoding 3675000:3680000
Encoding 3680000:3685000
Encoding 3685000:3690000
Encoding 3690000:3695000
Encoding 3695000:3700000
Encoding 3700000:3705000
Encoding 3705000:3710000
Encoding 3710000:3715000
Encoding 3715000:3720000
Encoding 3720000:3725000
Encoding 3725000:3730000
Encoding 3730000:3735000
Encoding 3735000:3740000
Encoding 3740000:3745000
Encoding 3745000:3750000
Encoding 3750000:3755000
Encoding 3755000:3760000
Encoding 3760000:3765000
Encoding 3765000:3770000
Encoding 3770000:3775000
Encoding 3775000:3780000
Encoding 3780000:3785000
Encoding 3785000:3790000
Encoding 3790000:3795000
Encoding 3795000:3800000
Encoding 3800000:3805000
Encoding 3805000:3810000
Encoding 3810000:3815000
Encoding 3815000:3820000
Encoding 3820000:3825000
Encoding 3825000:3830000
Encoding 3830000:3835000
Encoding 3835000:3840000
Encoding 3840000:3845000
Encoding 3845000:3850000
Encoding 3850000:3855000
Encoding 3855000:3860000
Encoding 3860000:3865000
Encoding 3865000:3870000
Encoding 3870000:3875000
Encoding 3875000:3880000
Encoding 3880000:3885000
Encoding 3885000:3890000
Encoding 3890000:3895000
Encoding 3895000:3900000
Encoding 3900000:3905000
Encoding 3905000:3910000
Encoding 3910000:3915000
Encoding 3915000:3920000
Encoding 3920000:3925000
Encoding 3925000:3930000
Encoding 3930000:3935000
Encoding 3935000:3940000
Encoding 3940000:3945000
Encoding 3945000:3950000
Encoding 3950000:3955000
Encoding 3955000:3960000
Encoding 3960000:3965000
Encoding 3965000:3970000
Encoding 3970000:3975000
Encoding 3975000:3980000
Encoding 3980000:3985000
Encoding 3985000:3990000
Encoding 3990000:3995000
Encoding 3995000:4000000
Encoding 4000000:4005000
Encoding 4005000:4010000
Encoding 4010000:4015000
Encoding 4015000:4020000
Encoding 4020000:4025000
Encoding 4025000:4030000
Encoding 4030000:4035000
Encoding 4035000:4040000
Encoding 4040000:4045000
Encoding 4045000:4050000
Encoding 4050000:4055000
Encoding 4055000:4060000
Encoding 4060000:4065000
Encoding 4065000:4070000
Encoding 4070000:4075000
Encoding 4075000:4080000
Encoding 4080000:4085000

In [12]:
documents.to_parquet(
    index_dir / "metadata.parquet",
    index=False
)

print(
    "Metadata saved:",
    index_dir / "metadata.parquet"
)

print(
    "Rows:",
    len(documents)
)

Metadata saved: ../data/indexes/product_comments_embedding/metadata.parquet
Rows: 6153060