In [42]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print(PROJECT_ROOT)

/home/ali/Desktop/projects/digikala-ai-assistant

In [65]:
from src.rag.config import load_config
from src.rag.retrieval.factory import RetrieverFactory
from src.rag.embedding.factory import EmbeddingFactory
from src.rag.retrieval.embedding import EmbeddingRetriever

In [59]:
config = load_config(
    "../configs/rag.yaml"
)

config

{'retriever': {'type': 'bm25', 'top_k': 5},
 'embedding': {'provider': 'sentence_transformer',
  'model': 'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2'}}

In [60]:
retriever = RetrieverFactory.create(
    config["retriever"]["type"],
    product_comments
)

In [61]:
product_comments = comments[
    comments.product_id == 5715766
].copy()


product_comments["search_text"] = (
    product_comments
    .apply(
        build_comment_text,
        axis=1
    )
)

In [62]:
results = retriever.retrieve(
    "آیا برای پوست چرب مناسب است؟",
    top_k=config["retriever"]["top_k"]
)

results[
    [
        "body",
        "rate",
        "score"
    ]
]

                                                  body  rate     score
108  اگر پوست چرب دارید خیلی مناسب نیست چون برق میو...   2.0  8.239756
153                   ضدآفتاب خیلی خوبیه برای پوست چرب   4.0  7.206134
220                                برای پوست چرب عالیه   5.0  7.206134
59                             قیمت مناسب در دیجی کالا   5.0  7.042508
125           برای پوست چرب نمیتونم بگم عالیه ولی خوبه   4.0  6.666359

In [64]:
embedding_model = EmbeddingFactory.create(
    provider=config["embedding"]["provider"],
    model_name=config["embedding"]["model"]
)

Loading weights: 100%|████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 16816.76it/s]

In [66]:
retriever = EmbeddingRetriever(
    product_comments,
    embedding_model
)

In [67]:
results = retriever.retrieve(
    "آیا برای پوست چرب مناسب است؟",
    top_k=config["retriever"]["top_k"]
)

results[
    [
        "body",
        "rate",
        "score"
    ]
]

                                                  body  rate     score
220                                برای پوست چرب عالیه   5.0  0.840207
153                   ضدآفتاب خیلی خوبیه برای پوست چرب   4.0  0.831016
43                               برای پوست چرب خوب بود   4.0  0.792578
196  سبک و خوبه ولی برعکس نظر دوستان صورت منو چرب م...   4.0  0.779009
116  به خاطر بافت فلوییدی و سبکش واقعا برای پوست ها...   5.0  0.759629