# 11 — Product Metadata Retrieval Debug

این notebook فقط retrieval محصول را بررسی می‌کند و **هیچ LLM call**
ندارد.

هدف: بررسی مستقیم موارد false-positive با تفکیک:

- BM25 rank / raw score
- Embedding rank / raw cosine
- RRF score
- lexical token/bigram overlap
- final metadata score

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from src.rag.config import load_config
from src.rag.embedding.factory import EmbeddingFactory
from src.rag.preprocessing.processor import TextProcessor
from src.rag.product_search import (
    ProductFAISSIndex,
    ProductBM25Index,
    ProductMetadataRetriever,
)

In [2]:
rag_config = load_config(
    PROJECT_ROOT
    / "configs"
    / "rag.yaml"
)

search_config = load_config(
    PROJECT_ROOT
    / "configs"
    / "product_search.yaml"
)

metadata_cfg = (
    search_config[
        "product_search"
    ][
        "metadata"
    ]
)

processor = TextProcessor()

embedding_model = (
    EmbeddingFactory.create(
        provider=rag_config[
            "embedding"
        ][
            "provider"
        ],
        model_name=rag_config[
            "embedding"
        ][
            "model"
        ],
    )
)

dense_index = (
    ProductFAISSIndex()
    .load(
        PROJECT_ROOT
        / "data"
        / "indexes"
        / "products_embedding"
    )
)

sparse_index = (
    ProductBM25Index(
        processor=processor
    )
    .load(
        PROJECT_ROOT
        / "data"
        / "indexes"
        / "products_bm25_tantivy"
    )
)

retriever = ProductMetadataRetriever(
    embedding_model=embedding_model,
    dense_index=dense_index,
    sparse_index=sparse_index,
    processor=processor,
    bm25_weight=metadata_cfg[
        "bm25_weight"
    ],
    embedding_weight=metadata_cfg[
        "embedding_weight"
    ],
    candidate_multiplier=metadata_cfg[
        "candidate_multiplier"
    ],
    brand_boost=metadata_cfg[
        "brand_boost"
    ],
    lexical_weight=metadata_cfg[
        "lexical_weight"
    ],
    rrf_k=metadata_cfg[
        "rrf_k"
    ],
    validate_index_alignment=metadata_cfg[
        "validate_index_alignment"
    ],
)

print("Product index alignment: OK")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Product index alignment: OK

In [3]:
queries = [
    "ضد آفتاب پوست چرب که جوش نزنه",
    "شامپو ضد ریزش سریتا",
    "کرم آبرسان سبک و زود جذب",
]

debug_columns = [
    "id",
    "title_fa",
    "Brand",
    "Category2",
    "metadata_score",
    "rrf_score",
    "lexical_score",
    "token_overlap",
    "bigram_overlap",
    "bm25_rank",
    "embedding_rank",
    "bm25_raw_score",
    "embedding_raw_score",
    "brand_match",
]

for query in queries:
    print()
    print("=" * 100)
    print("QUERY:", query)

    results = retriever.retrieve(
        query,
        top_k=20,
    )

    display(
        results[
            debug_columns
        ]
    )

====================================================================================================
QUERY: ضد آفتاب پوست چرب که جوش نزنه

,id,title_fa,Brand,Category2,metadata_score,rrf_score,lexical_score,token_overlap,bigram_overlap,bm25_rank,embedding_rank,bm25_raw_score,embedding_raw_score,brand_match
0,1110394,کرم ضد آفتاب رنگی اریکه مدل SPF50 مناسب پوست ه...,اریکه,کرم ضد آفتاب,0.727207,0.823153,0.503333,0.666667,0.2,4.0,28.0,32.729515,0.618812,0.0
1,10985328,فلوئید ضد آفتاب بی رنگ نوکس SPF50 مدل LIGHT من...,نوکس,کرم ضد آفتاب,0.727207,0.823153,0.503333,0.666667,0.2,28.0,4.0,30.930351,0.652808,0.0
2,11286406,فلوئید ضد آفتاب بی رنگ اوریاژ +SPF50 مدل Hysea...,اوریاژ,کرم ضد آفتاب,0.704858,0.791226,0.503333,0.666667,0.2,29.0,8.0,30.930351,0.646624,0.0
3,9156746,کرم ضد آفتاب رنگی بیکن +SPF50 شماره +1 مناسب پ...,بیکن,کرم ضد آفتاب,0.683799,0.761141,0.503333,0.666667,0.2,6.0,42.0,32.194176,0.608636,0.0
4,6733478,فلوئید ضد آفتاب بی رنگ الارو SPF50 مدل Ultra L...,الارو,کرم ضد آفتاب,0.668576,0.739394,0.503333,0.666667,0.2,50.0,6.0,30.452507,0.651996,0.0
5,5536401,کرم ضد آفتاب رنگی سینره +SPF60 مدل 8411 مناسب ...,سینره,کرم ضد آفتاب,0.668203,0.738861,0.503333,0.666667,0.2,13.0,35.0,32.194176,0.611982,0.0
6,12243791,کرم ضد آفتاب بدون رنگ SPF 30 تینولا مدل Tino S...,متفرقه,کرم ضد آفتاب,0.657999,0.724284,0.503333,0.666667,0.2,67.0,3.0,28.446892,0.657175,0.0
7,183277,کرم ضد آفتاب رنگی الارو SPF50 مدل Teinte Fonce...,الارو,کرم ضد آفتاب,0.647445,0.709207,0.503333,0.666667,0.2,20.0,33.0,31.933105,0.612756,0.0
8,12390858,کرم ضد آفتاب بدون رنگ سیلوژه SPF 50 مدل TEXTUR...,سیلوژه,کرم ضد آفتاب,0.632598,0.687997,0.503333,0.666667,0.2,64.0,9.0,28.938171,0.644173,0.0
9,12550788,کرم ضد آفتاب رنگی اریکه SPF 50 مدل Solarie And...,اریکه,کرم ضد آفتاب,0.605017,0.648596,0.503333,0.666667,0.2,69.0,14.0,27.972605,0.635154,0.0
10,12271621,کرم ضد آفتاب بدون رنگ ژوت SPF 50 مدل smooth si...,ژوت,کرم ضد آفتاب,0.598632,0.639474,0.503333,0.666667,0.2,56.0,21.0,29.989372,0.627561,0.0
11,11398256,فلوئید ضد آفتاب بی رنگ ویشی SPF50 مدل مات مناس...,ویشی,کرم ضد آفتاب,0.587755,0.623936,0.503333,0.666667,0.2,30.0,47.0,30.930351,0.601928,0.0
12,1968567,کرم ضد آفتاب بی رنگ مای سری فارما مدل SPF50 من...,مای,کرم ضد آفتاب,0.585907,0.621296,0.503333,0.666667,0.2,48.0,30.0,30.452507,0.618041,0.0
13,442478,کرم ضد آفتاب رنگی ژاک آندرل پاریس مخصوص پوست چ...,ژاک آندرل پاریس,کرم ضد آفتاب,0.578704,0.581005,0.573333,0.666667,0.4,46.0,44.0,30.452507,0.607999,0.0
14,12362928,کرم ضد آفتاب رنگی رزالیا SPF 50 مدل 2 ‌مناسب پ...,رزالیا,کرم ضد آفتاب,0.575754,0.606791,0.503333,0.666667,0.2,63.0,25.0,28.938171,0.623359,0.0
15,2906254,کرم ضد آفتاب بی رنگ مای +SPF50 مدل فارما سان س...,مای,کرم ضد آفتاب,0.571268,0.600382,0.503333,0.666667,0.2,55.0,31.0,29.989372,0.616900,0.0
16,9171599,ژل ضد آفتاب بی رنگ آردن سولاریس SPF50 مدل Clea...,آردن سولاریس,کرم ضد آفتاب,0.563801,0.589716,0.503333,0.666667,0.2,41.0,46.0,30.452507,0.605065,0.0
17,715347,کرم ضدآفتاب و ضد لک رنگی لافارر مدل SPF 40-Lig...,لافارر,کرم ضد آفتاب,0.559379,0.583399,0.503333,0.666667,0.2,71.0,27.0,27.691151,0.620620,0.0
18,2410578,کرم ضد آفتاب رنگی مدیسان مدل Tinted SPF 60 منا...,مدیسان,کرم ضد آفتاب,0.551312,0.571875,0.503333,0.666667,0.2,36.0,60.0,30.930351,0.596603,0.0
19,734627,کرم ضد آفتاب و ضدچروک بی رنگ دکتر ژیلا مدل Spf...,دکتر ژیلا,کرم ضد آفتاب,0.548218,0.567454,0.503333,0.666667,0.2,47.0,48.0,30.452507,0.600882,0.0

====================================================================================================
QUERY: شامپو ضد ریزش سریتا

,id,title_fa,Brand,Category2,metadata_score,rrf_score,lexical_score,token_overlap,bigram_overlap,bm25_rank,embedding_rank,bm25_raw_score,embedding_raw_score,brand_match
0,711943,شامپو ضد ریزش سریتا مدل پرومین مناسب برای موها...,سریتا,شامپو مو,0.711111,0.484127,1.000000,1.00,1.000000,3.0,NaN,35.896019,NaN,1.0
1,6552521,شامپو تقویت کننده و ضد ریزش سریتا مدل Fortifyi...,سریتا,شامپو مو,0.692000,0.500000,0.883333,1.00,0.666667,1.0,NaN,36.173233,NaN,1.0
2,1147482,شامپو ضد ریزش مو فورکاپیل مدل procapil حجم 200...,فورکاپیل,شامپو مو,0.681776,0.665038,0.720833,0.75,0.666667,73.0,10.0,23.428490,0.696847,0.0
3,296253,شامپو ضد ریزش مو مورست حجم 250 میلی لیتر,مورست,شامپو مو,0.680435,0.663122,0.720833,0.75,0.666667,31.0,33.0,24.325674,0.662043,0.0
4,8021274,شامپو ضد ریزش مو سریتا مدل مینوتا حجم 200 میلی...,سریتا,شامپو مو,0.674769,0.469231,0.883333,1.00,0.666667,5.0,NaN,35.571182,NaN,1.0
5,10324133,شامپو ضد ریزش مو گلیس مدل NUTRIBAL حجم 500 میل...,گلیس,شامپو مو,0.667111,0.644087,0.720833,0.75,0.666667,54.0,21.0,23.428490,0.675327,0.0
6,3832629,شامپو ضد ریزش مو سریتا مدل مینوتا مناسب برای م...,سریتا,شامپو مو,0.666925,0.455224,0.883333,1.00,0.666667,7.0,NaN,34.989395,NaN,1.0
7,471187,شامپو تقویت کننده و ضد ریزش سریتا مدل کافئین م...,سریتا,شامپو مو,0.659536,0.442029,0.883333,1.00,0.666667,9.0,NaN,33.882515,NaN,1.0
8,476822,تونیک ضد ریزش مو سریتا مدل پرومین حجم 60 میلی ...,سریتا,شامپو مو,0.659484,0.491935,0.766667,1.00,0.333333,2.0,NaN,35.905472,NaN,1.0
9,6506826,شامپو تقویت کننده و ضد ریزش مو سریتا مدل قهوه ...,سریتا,شامپو مو,0.650875,0.476562,0.766667,1.00,0.333333,4.0,NaN,35.571182,NaN,1.0
10,11144034,شامپو ضد ریزش مو دیترون مدل کافیین حجم 300 میل...,دیترون,شامپو مو,0.648479,0.617470,0.720833,0.75,0.666667,62.0,23.0,23.428490,0.673463,0.0
11,471143,شامپو تقویت کننده و ضد ریزش سریتا مدل فورتی فا...,سریتا,شامپو مو,0.645973,0.417808,0.883333,1.00,0.666667,13.0,NaN,33.355579,NaN,1.0
12,3832600,شامپو ضد ریزش مو سریتا مدل مینوتا مناسب برای م...,سریتا,شامپو مو,0.642811,0.412162,0.883333,1.00,0.666667,14.0,NaN,33.355579,NaN,1.0
13,11254633,شامپو تقویت کننده و ضد ریزش مو سریتا مدل جوانه...,سریتا,شامپو مو,0.642788,0.462121,0.766667,1.00,0.333333,6.0,NaN,34.989395,NaN,1.0
14,471119,شامپو تقویت کننده و ضد ریزش مو سریتا مدل Forti...,سریتا,شامپو مو,0.635176,0.448529,0.766667,1.00,0.333333,8.0,NaN,33.882515,NaN,1.0
15,8021212,شامپو تقویت کننده و ضد ریزش سریتا مدل کافئین م...,سریتا,شامپو مو,0.633818,0.396104,0.883333,1.00,0.666667,17.0,NaN,32.350521,NaN,1.0
16,8020989,شامپو تقویت کننده و ضد ریزش مو سریتا مدل 03 حج...,سریتا,شامپو مو,0.628000,0.435714,0.766667,1.00,0.333333,10.0,NaN,33.882515,NaN,1.0
17,712001,تونیک ضد ریزش و تقویت کننده مو سریتا مدل T2 حج...,سریتا,شامپو مو,0.624563,0.429577,0.766667,1.00,0.333333,11.0,NaN,33.826389,NaN,1.0
18,3832551,تونیک ضد ریزش مو سریتا مدل مینوتا حجم 50 میلی ...,سریتا,سرم و اسپری مو,0.621222,0.423611,0.766667,1.00,0.333333,12.0,NaN,33.484879,NaN,1.0
19,811482,پک شامپو تقویت کننده و ضد ریزش سریتا مدل Caffe...,سریتا,تقویت کننده مو,0.620293,0.371951,0.883333,1.00,0.666667,22.0,NaN,31.412603,NaN,1.0

====================================================================================================
QUERY: کرم آبرسان سبک و زود جذب

,id,title_fa,Brand,Category2,metadata_score,rrf_score,lexical_score,token_overlap,bigram_overlap,bm25_rank,embedding_rank,bm25_raw_score,embedding_raw_score,brand_match
0,9585339,کرم آبرسان ناک مدل حاوی پروپولیس,ناک,کرم مرطوب کننده و نرم کننده,0.660996,0.795351,0.3475,0.4,0.25,3.0,38.0,17.801384,0.658882,0.0
1,9284669,کرم آبرسان سیمپل مدل Light حجم 125 میلی لیتر,سیمپل,کرم مرطوب کننده و نرم کننده,0.532131,0.611258,0.3475,0.4,0.25,57.0,27.0,16.745489,0.667794,0.0
2,3347106,کرم آبرسان پانی دراگ مدل Light حجم 150 میلی لیتر,پانی دراگ,کرم مرطوب کننده و نرم کننده,0.454250,0.500000,0.3475,0.4,0.25,NaN,1.0,NaN,0.732426,0.0
3,6282840,کرم آبرسان زیکسار مدل آبرسان و ضد چروک حجم 50 ...,زیکسار,کرم مرطوب کننده و نرم کننده,0.448605,0.491935,0.3475,0.4,0.25,2.0,NaN,18.575668,NaN,0.0
4,6556015,کرم آبرسان نوتروژنا مدل Besleyiciحجم 200میلی لیتر,نوتروژینا,کرم مرطوب کننده و نرم کننده,0.432712,0.469231,0.3475,0.4,0.25,5.0,NaN,17.434475,NaN,0.0
5,7120460,شورت گنی زنانه مدل جذب رنگ کرم,متفرقه,لباس زیر زنانه,0.428000,0.500000,0.2600,0.4,0.00,1.0,NaN,18.802958,NaN,0.0
6,4427742,کرم آبرسان کامان سری واتربمب مدل 003 حجم 200 م...,کامان,کرم مرطوب کننده و نرم کننده,0.427735,0.462121,0.3475,0.4,0.25,6.0,NaN,17.429705,NaN,0.0
7,4428092,کرم آبرسان کامان سری واتربمب مدل 002 حجم 200 م...,کامان,کرم مرطوب کننده و نرم کننده,0.422907,0.455224,0.3475,0.4,0.25,7.0,NaN,17.429705,NaN,0.0
8,4428508,کرم آبرسان کامان سری واتربمب مدل 001 حجم 200 م...,کامان,کرم مرطوب کننده و نرم کننده,0.418221,0.448529,0.3475,0.4,0.25,8.0,NaN,17.429705,NaN,0.0
9,5927558,کرم آبرسان کامان مدل Collagen حجم 500 میلی لیت...,کامان,کرم مرطوب کننده و نرم کننده,0.413670,0.442029,0.3475,0.4,0.25,9.0,NaN,17.429705,NaN,0.0
10,574876,کرم کامل آبرسان تگودر مدل اکسیژن O2,تگودر,کرم مرطوب کننده و نرم کننده,0.411594,0.476562,0.2600,0.4,0.00,4.0,NaN,17.434475,NaN,0.0
11,10530170,کرم آبرسان فریدن مدل 01 حجم 50 میلی لیتر,فریدن,کرم مرطوب کننده و نرم کننده,0.411460,0.438872,0.3475,0.4,0.25,80.0,78.0,16.745489,0.640512,0.0
12,7968583,کرم آبرسان الوندرا مدل EL-Blueberry حجم 250 می...,متفرقه,کرم مرطوب کننده و نرم کننده,0.409250,0.435714,0.3475,0.4,0.25,10.0,NaN,17.429705,NaN,0.0
13,4428649,کرم آبرسان کامان سری واتربمب مدل 001 حجم 200 م...,کامان,کرم مرطوب کننده و نرم کننده,0.404954,0.429577,0.3475,0.4,0.25,11.0,NaN,17.235344,NaN,0.0
14,7209633,کرم آبرسان شون مدل COLLAGEN حجم 500 میلی لیتر ...,شون,کرم مرطوب کننده و نرم کننده,0.400778,0.423611,0.3475,0.4,0.25,12.0,NaN,17.235344,NaN,0.0
15,7968620,کرم آبرسان الوندرا مدل Aleo vera حجم 250 میلی ...,متفرقه,کرم مرطوب کننده و نرم کننده,0.396716,0.417808,0.3475,0.4,0.25,13.0,NaN,17.235344,NaN,0.0
16,9087506,کرم آبرسان ایمجز مدل کرم شیر گاو حجم 60 میلی لیتر,ایمجز,کرم مرطوب کننده و نرم کننده,0.388917,0.406667,0.3475,0.4,0.25,15.0,NaN,17.093771,NaN,0.0
17,9586649,کرم آبرسان ناک مدل پروپولیس 60 میلی لیتر,ناک,کرم مرطوب کننده و نرم کننده,0.385171,0.401316,0.3475,0.4,0.25,16.0,NaN,17.082834,NaN,0.0
18,6410900,کرم روشن کننده آرتوینا مدل خیار حجم 50 میلی لیتر,متفرقه,کرم روشن کننده,0.383355,0.491935,0.1300,0.2,0.00,NaN,2.0,NaN,0.716587,0.0
19,10705225,کرم آبرسان اسکایلر مدل آرگان حجم 150میلی لیتر,متفرقه,کرم مرطوب کننده و نرم کننده,0.381523,0.396104,0.3475,0.4,0.25,17.0,NaN,17.082834,NaN,0.0